name: Publish Function App .NET container image to GitHub

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'src/Azure.AISearch.FunctionApp.DotNet/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build --no-cache -t pia/azure-aisearch-functionapp-dotnet:latest -f ./src/Azure.AISearch.FunctionApp.DotNet/Dockerfile ./src/Azure.AISearch.FunctionApp.DotNet
    - name: Push Docker Image to GitHub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag pia/azure-aisearch-functionapp-dotnet:latest ghcr.io/pia/azure-aisearch-functionapp-dotnet:latest
        docker push ghcr.io/pia/azure-aisearch-functionapp-dotnet:latest